"""empty message

Revision ID: 26f41a8c85c4
Revises: 888185303544
Create Date: 2023-07-31 12:36:05.158006

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26f41a8c85c4'
down_revision = '888185303544'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('department', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total', sa.String(), nullable=True))

    with op.batch_alter_table('school', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total', sa.String(), nullable=True))

    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total', sa.String(), nullable=True))

    with op.batch_alter_table('year', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('year', schema=None) as batch_op:
        batch_op.drop_column('total')

    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.drop_column('total')

    with op.batch_alter_table('school', schema=None) as batch_op:
        batch_op.drop_column('total')

    with op.batch_alter_table('department', schema=None) as batch_op:
        batch_op.drop_column('total')

    # ### end Alembic commands ###
