"""empty message

Revision ID: 2d881d3dda8d
Revises: d7ec6c57a465
Create Date: 2023-08-07 10:48:32.910552

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d881d3dda8d'
down_revision = 'd7ec6c57a465'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('beneficianies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name_beneficianies', sa.String(length=100), nullable=True),
    sa.Column('address_beneficianies', sa.String(length=100), nullable=True),
    sa.Column('other_beneficianies', sa.String(length=100), nullable=True),
    sa.Column('gender_beneficianies', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('department',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('total', sa.String(), nullable=True),
    sa.Column('department', sa.String(), nullable=True),
    sa.Column('school', sa.String(), nullable=True),
    sa.Column('program', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dependent',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('next_of_kin', sa.String(length=100), nullable=True),
    sa.Column('relationship', sa.String(length=100), nullable=True),
    sa.Column('address_kin', sa.String(length=100), nullable=True),
    sa.Column('gender_kin', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('financial',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bank_number', sa.String(length=100), nullable=True),
    sa.Column('bank_name', sa.String(length=100), nullable=True),
    sa.Column('bank_branch', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('id',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ghana_card', sa.String(length=100), nullable=True),
    sa.Column('snit_number', sa.String(length=100), nullable=True),
    sa.Column('tin_number', sa.String(length=100), nullable=True),
    sa.Column('immigration_number', sa.String(length=100), nullable=True),
    sa.Column('address', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lecturers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=20), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('password', sa.String(length=200), nullable=True),
    sa.Column('school', sa.String(length=20), nullable=True),
    sa.Column('image', sa.String(length=10), nullable=True),
    sa.Column('telephone', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('school',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('total', sa.String(), nullable=True),
    sa.Column('department', sa.String(), nullable=True),
    sa.Column('school', sa.String(), nullable=True),
    sa.Column('program', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('staff',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('surname', sa.String(), nullable=True),
    sa.Column('firstname', sa.String(), nullable=True),
    sa.Column('maiden_name', sa.String(), nullable=True),
    sa.Column('offical_email', sa.String(), nullable=True),
    sa.Column('personal_email', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('position', sa.String(), nullable=True),
    sa.Column('member_staff', sa.String(), nullable=True),
    sa.Column('department_directorate_unit', sa.String(), nullable=True),
    sa.Column('number', sa.String(), nullable=True),
    sa.Column('gender', sa.String(), nullable=True),
    sa.Column('rank', sa.String(), nullable=True),
    sa.Column('grade', sa.String(), nullable=True),
    sa.Column('job_title', sa.String(), nullable=True),
    sa.Column('employment_status', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('student',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('total', sa.String(), nullable=True),
    sa.Column('department', sa.String(), nullable=True),
    sa.Column('program', sa.String(), nullable=True),
    sa.Column('email', sa.String(length=20), nullable=True),
    sa.Column('school', sa.String(), nullable=True),
    sa.Column('telephone', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('image', sa.String(), nullable=True),
    sa.Column('bio', sa.String(), nullable=True),
    sa.Column('current_company', sa.String(), nullable=True),
    sa.Column('socials', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('year',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('total', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('year')
    op.drop_table('student')
    op.drop_table('staff')
    op.drop_table('school')
    op.drop_table('lecturers')
    op.drop_table('id')
    op.drop_table('financial')
    op.drop_table('dependent')
    op.drop_table('department')
    op.drop_table('beneficianies')
    # ### end Alembic commands ###
